<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DocsController extends Controller
{
    /**
     * Display Swagger UI documentation page.
     *
     * Route: GET /docs
     */
    public function index()
    {
        return view('swagger.index');
    }

    /**
     * Return Swagger JSON file generated by L5-Swagger.
     *
     * Route: GET /docs/json
     */
    public function json()
    {
        $path = storage_path('api-docs/swagger.json');

        if (!file_exists($path)) {
            return response()->json([
                'status' => 'error',
                'message' => 'Swagger JSON not found. Please run: php artisan l5-swagger:generate'
            ], 404);
        }

        return response()->file($path, [
            'Content-Type' => 'application/json'
        ]);
    }
}
